name: Update Destiny 2 Manifest

on:
  schedule:
    # Run every Tuesday at 1:30 PM EST (18:30 UTC)
    - cron: '30 18 * * 2'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Pull and save manifest
      env:
        BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ secrets.MANIFEST_REPO }}
        GITHUB_BRANCH: main
      run: |
        node scripts/update-manifest.js
    
    - name: Notify on success
      if: success()
      run: echo "✅ Manifest updated successfully at $(date)"
    
    - name: Notify on failure
      if: failure()
      run: echo "❌ Manifest update failed at $(date)"